# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28

# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five
# hundred divisors?

# Execution Time: 12.021s

# Except the square root of its value, all triangle numbers' divisors are
# paired. So we just need to count all the divisors of new generated triangle
# numbers up to their square root, and stop when we get to 250.

triangle_nbs = [nil, 1]
divisors = []
nb_divisors = 500

while divisors.length < (nb_divisors/2.0).round   # 'round' in case of odd
  divisors = []									  #  number of divisors
  triangle_nbs << (triangle_nbs.last + triangle_nbs.length) 
  (1..Math.sqrt(triangle_nbs.last)).each do |n|
    divisors << n if triangle_nbs.last % n == 0
  end
end

puts "More than 500 divisors: " + triangle_nbs.last.to_s